"use client";

import type { HTMLAttributes } from "react";
import type { SelectItemType } from "@/components";

/**
 * List of countries with their respective country code, flag, phone code, and phone mask.
 */
export const countries = [
  {
    name: "Afghanistan",
    code: "AF",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/af.svg",
    phoneCode: "93",
    phoneMask: "+93-##-###-####",
  },
  {
    name: "Albania",
    code: "AL",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/al.svg",
    phoneCode: "355",
    phoneMask: "+355 (###) ###-###",
  },
  {
    name: "Algeria",
    code: "DZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/dz.svg",
    phoneCode: "213",
    phoneMask: "+213-##-###-####",
  },
  {
    name: "Andorra",
    code: "AD",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ad.svg",
    phoneCode: "376",
    phoneMask: "+376-###-###",
  },
  {
    name: "Angola",
    code: "AO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ao.svg",
    phoneCode: "244",
    phoneMask: "+244 (###) ###-###",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ag.svg",
    phoneCode: "+1-268",
    phoneMask: "+1 (268) ###-####",
  },
  {
    name: "Argentina",
    code: "AR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ar.svg",
    phoneCode: "54",
    phoneMask: "+54 (###) ###-####",
  },
  {
    name: "Armenia",
    code: "AM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/am.svg",
    phoneCode: "374",
    phoneMask: "+374-##-###-###",
  },
  {
    name: "Australia",
    code: "AU",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/au.svg",
    phoneCode: "61",
    phoneMask: "+61-#-####-####",
  },
  {
    name: "Austria",
    code: "AT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/at.svg",
    phoneCode: "43",
    phoneMask: "+43 (###) ###-####",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/az.svg",
    phoneCode: "994",
    phoneMask: "+994-##-###-##-##",
  },
  {
    name: "Bahamas",
    code: "BS",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bs.svg",
    phoneCode: "+1-242",
    phoneMask: "+1 (242) ###-####",
  },
  {
    name: "Bahrain",
    code: "BH",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bh.svg",
    phoneCode: "973",
    phoneMask: "+973-####-####",
  },
  {
    name: "Bangladesh",
    code: "BD",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bd.svg",
    phoneCode: "880",
    phoneMask: "+880-##-###-###",
  },
  {
    name: "Barbados",
    code: "BB",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bb.svg",
    phoneCode: "+1-246",
    phoneMask: "+1 (246) ###-####",
  },
  {
    name: "Belarus",
    code: "BY",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/by.svg",
    phoneCode: "375",
    phoneMask: "+375 (##) ###-##-##",
  },
  {
    name: "Belgium",
    code: "BE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/be.svg",
    phoneCode: "32",
    phoneMask: "+32 (###) ###-###",
  },
  {
    name: "Belize",
    code: "BZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bz.svg",
    phoneCode: "501",
    phoneMask: "+501-###-####",
  },
  {
    name: "Benin",
    code: "BJ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bj.svg",
    phoneCode: "229",
    phoneMask: "+229-##-##-####",
  },
  {
    name: "Bhutan",
    code: "BT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bt.svg",
    phoneCode: "975",
    phoneMask: "+975-#-###-###",
  },
  {
    name: "Bolivia",
    code: "BO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bo.svg",
    phoneCode: "591",
    phoneMask: "+591-#-###-####",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ba.svg",
    phoneCode: "387",
    phoneMask: "+387-##-####",
  },
  {
    name: "Botswana",
    code: "BW",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bw.svg",
    phoneCode: "267",
    phoneMask: "+267-##-###-###",
  },
  {
    name: "Brazil",
    code: "BR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/br.svg",
    phoneCode: "55",
    phoneMask: "+55 (##) 9####-####",
  },
  {
    name: "Brunei",
    code: "BN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bn.svg",
    phoneCode: "673",
    phoneMask: "+673-###-####",
  },
  {
    name: "Bulgaria",
    code: "BG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bg.svg",
    phoneCode: "359",
    phoneMask: "+359 (###) ###-###",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bf.svg",
    phoneCode: "226",
    phoneMask: "+226-##-##-####",
  },
  {
    name: "Burundi",
    code: "BI",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/bi.svg",
    phoneCode: "257",
    phoneMask: "+257-##-##-####",
  },
  {
    name: "Cambodia",
    code: "KH",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/kh.svg",
    phoneCode: "855",
    phoneMask: "+855-##-###-###",
  },
  {
    name: "Cameroon",
    code: "CM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cm.svg",
    phoneCode: "237",
    phoneMask: "+237-####-####",
  },
  {
    name: "Canada",
    code: "CA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ca.svg",
    phoneCode: "1",
    phoneMask: "+1 (###) ###-####",
  },
  {
    name: "Central African Republic",
    code: "CF",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cf.svg",
    phoneCode: "236",
    phoneMask: "+236-##-##-####",
  },
  {
    name: "Chad",
    code: "TD",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/td.svg",
    phoneCode: "235",
    phoneMask: "+235-##-##-##-##",
  },
  {
    name: "Chile",
    code: "CL",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cl.svg",
    phoneCode: "56",
    phoneMask: "+56-#-####-####",
  },
  {
    name: "China",
    code: "CN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cn.svg",
    phoneCode: "86",
    phoneMask: "+86-##-#####-#####",
  },
  {
    name: "Colombia",
    code: "CO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/co.svg",
    phoneCode: "57",
    phoneMask: "+57 (###) ###-####",
  },
  {
    name: "Comoros",
    code: "KM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/km.svg",
    phoneCode: "269",
    phoneMask: "+269-##-#####",
  },
  {
    name: "Costa Rica",
    code: "CR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cr.svg",
    phoneCode: "506",
    phoneMask: "+506-####-####",
  },
  {
    name: "Croatia",
    code: "HR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/hr.svg",
    phoneCode: "385",
    phoneMask: "+385-##-###-###",
  },
  {
    name: "Cuba",
    code: "CU",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cu.svg",
    phoneCode: "53",
    phoneMask: "+53-#-###-####",
  },
  {
    name: "Cyprus",
    code: "CY",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cy.svg",
    phoneCode: "357",
    phoneMask: "+357-##-###-###",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cz.svg",
    phoneCode: "420",
    phoneMask: "+420 (###) ###-###",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/cd.svg",
    phoneCode: "243",
    phoneMask: "+243 (###) ###-###",
  },
  {
    name: "Denmark",
    code: "DK",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/dk.svg",
    phoneCode: "45",
    phoneMask: "+45-##-##-##-##",
  },
  {
    name: "Djibouti",
    code: "DJ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/dj.svg",
    phoneCode: "253",
    phoneMask: "+253-##-##-##-##",
  },
  {
    name: "Dominica",
    code: "DM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/dm.svg",
    phoneCode: "+1-767",
    phoneMask: "+1 (767) ###-####",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/do.svg",
    phoneCode: "+1-809 and 1-829",
    phoneMask: "+1 (849) ###-####",
  },
  {
    name: "East Timor",
    code: "TL",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tl.svg",
    phoneCode: "670",
    phoneMask: "+670-78#-#####",
  },
  {
    name: "Ecuador",
    code: "EC",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ec.svg",
    phoneCode: "593",
    phoneMask: "+593-#-###-####",
  },
  {
    name: "Egypt",
    code: "EG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/eg.svg",
    phoneCode: "20",
    phoneMask: "+20 (###) ###-####",
  },
  {
    name: "El Salvador",
    code: "SV",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sv.svg",
    phoneCode: "503",
    phoneMask: "+503-##-##-####",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gq.svg",
    phoneCode: "240",
    phoneMask: "+240-##-###-####",
  },
  {
    name: "Eritrea",
    code: "ER",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/er.svg",
    phoneCode: "291",
    phoneMask: "+291-#-###-###",
  },
  {
    name: "Estonia",
    code: "EE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ee.svg",
    phoneCode: "372",
    phoneMask: "+372-###-####",
  },
  {
    name: "Eswatini",
    code: "SZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sz.svg",
    phoneCode: "268",
    phoneMask: "+268-##-##-####",
  },
  {
    name: "Ethiopia",
    code: "ET",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/et.svg",
    phoneCode: "251",
    phoneMask: "+251-##-###-####",
  },
  {
    name: "Fiji",
    code: "FJ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/fj.svg",
    phoneCode: "679",
    phoneMask: "+679-##-#####",
  },
  {
    name: "Finland",
    code: "FI",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/fi.svg",
    phoneCode: "358",
    phoneMask: "+358 (###) ###-##-##",
  },
  {
    name: "France",
    code: "FR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/fr.svg",
    phoneCode: "33",
    phoneMask: "+590 (###) ###-###",
  },
  {
    name: "Gabon",
    code: "GA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ga.svg",
    phoneCode: "241",
    phoneMask: "+241-#-##-##-##",
  },
  {
    name: "Gambia",
    code: "GM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gm.svg",
    phoneCode: "220",
    phoneMask: "+220 (###) ##-##",
  },
  {
    name: "Georgia",
    code: "GE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ge.svg",
    phoneCode: "995",
    phoneMask: "+995 (###) ###-###",
  },
  {
    name: "Germany",
    code: "DE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/de.svg",
    phoneCode: "49",
    phoneMask: "+49-###-###",
  },
  {
    name: "Ghana",
    code: "GH",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gh.svg",
    phoneCode: "233",
    phoneMask: "+233 (###) ###-###",
  },
  {
    name: "Greece",
    code: "GR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gr.svg",
    phoneCode: "30",
    phoneMask: "+30 (###) ###-####",
  },
  {
    name: "Grenada",
    code: "GD",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gd.svg",
    phoneCode: "+1-473",
    phoneMask: "+1 (473) ###-####",
  },
  {
    name: "Guatemala",
    code: "GT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gt.svg",
    phoneCode: "502",
    phoneMask: "+502-#-###-####",
  },
  {
    name: "Guinea",
    code: "GN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gn.svg",
    phoneCode: "224",
    phoneMask: "+224-##-###-###",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gw.svg",
    phoneCode: "245",
    phoneMask: "+245-#-######",
  },
  {
    name: "Guyana",
    code: "GY",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gy.svg",
    phoneCode: "592",
    phoneMask: "+592-###-####",
  },
  {
    name: "Haiti",
    code: "HT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ht.svg",
    phoneCode: "509",
    phoneMask: "+509-##-##-####",
  },
  {
    name: "Honduras",
    code: "HN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/hn.svg",
    phoneCode: "504",
    phoneMask: "+504-####-####",
  },
  {
    name: "Hungary",
    code: "HU",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/hu.svg",
    phoneCode: "36",
    phoneMask: "+36 (###) ###-###",
  },
  {
    name: "Iceland",
    code: "IS",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/is.svg",
    phoneCode: "354",
    phoneMask: "+354-###-####",
  },
  {
    name: "India",
    code: "IN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/in.svg",
    phoneCode: "91",
    phoneMask: "+91 (####) ###-###",
  },
  {
    name: "Indonesia",
    code: "ID",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/id.svg",
    phoneCode: "62",
    phoneMask: "+62 (8##) ###-##-###",
  },
  {
    name: "Iran",
    code: "IR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ir.svg",
    phoneCode: "98",
    phoneMask: "+98 (###) ###-####",
  },
  {
    name: "Iraq",
    code: "IQ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/iq.svg",
    phoneCode: "964",
    phoneMask: "+964 (###) ###-####",
  },
  {
    name: "Ireland",
    code: "IE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ie.svg",
    phoneCode: "353",
    phoneMask: "+353 (###) ###-###",
  },
  {
    name: "Israel",
    code: "IL",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/il.svg",
    phoneCode: "972",
    phoneMask: "+972-#-###-####",
  },
  {
    name: "Italy",
    code: "IT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/it.svg",
    phoneCode: "39",
    phoneMask: "+39 (###) ####-###",
  },
  {
    name: "Jamaica",
    code: "JM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/jm.svg",
    phoneCode: "+1-876",
    phoneMask: "+1 (876) ###-####",
  },
  {
    name: "Japan",
    code: "JP",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/jp.svg",
    phoneCode: "81",
    phoneMask: "+81 (###) ###-###",
  },
  {
    name: "Jordan",
    code: "JO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/jo.svg",
    phoneCode: "962",
    phoneMask: "+962-#-####-####",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/kz.svg",
    phoneCode: "7",
    phoneMask: "+7 (7##) ###-##-##",
  },
  {
    name: "Kenya",
    code: "KE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ke.svg",
    phoneCode: "254",
    phoneMask: "+254-###-######",
  },
  {
    name: "Kiribati",
    code: "KI",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ki.svg",
    phoneCode: "686",
    phoneMask: "+686-##-###",
  },
  {
    name: "Kuwait",
    code: "KW",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/kw.svg",
    phoneCode: "965",
    phoneMask: "+965-####-####",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/kg.svg",
    phoneCode: "996",
    phoneMask: "+996 (###) ###-###",
  },
  {
    name: "Laos",
    code: "LA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/la.svg",
    phoneCode: "856",
    phoneMask: "+856-##-###-###",
  },
  {
    name: "Latvia",
    code: "LV",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/lv.svg",
    phoneCode: "371",
    phoneMask: "+371-##-###-###",
  },
  {
    name: "Lebanon",
    code: "LB",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/lb.svg",
    phoneCode: "961",
    phoneMask: "+961-#-###-###",
  },
  {
    name: "Lesotho",
    code: "LS",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ls.svg",
    phoneCode: "266",
    phoneMask: "+266-#-###-####",
  },
  {
    name: "Liberia",
    code: "LR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/lr.svg",
    phoneCode: "231",
    phoneMask: "+231-##-###-###",
  },
  {
    name: "Libya",
    code: "LY",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ly.svg",
    phoneCode: "218",
    phoneMask: "+218-21-###-####",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/li.svg",
    phoneCode: "423",
    phoneMask: "+423 (###) ###-####",
  },
  {
    name: "Lithuania",
    code: "LT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/lt.svg",
    phoneCode: "370",
    phoneMask: "+370 (###) ##-###",
  },
  {
    name: "Luxembourg",
    code: "LU",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/lu.svg",
    phoneCode: "352",
    phoneMask: "+352 (###) ###-###",
  },
  {
    name: "Madagascar",
    code: "MG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mg.svg",
    phoneCode: "261",
    phoneMask: "+261-##-##-#####",
  },
  {
    name: "Malawi",
    code: "MW",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mw.svg",
    phoneCode: "265",
    phoneMask: "+265-#-####-####",
  },
  {
    name: "Malaysia",
    code: "MY",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/my.svg",
    phoneCode: "60",
    phoneMask: "+60-#-###-###",
  },
  {
    name: "Maldives",
    code: "MV",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mv.svg",
    phoneCode: "960",
    phoneMask: "+960-###-####",
  },
  {
    name: "Mali",
    code: "ML",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ml.svg",
    phoneCode: "223",
    phoneMask: "+223-##-##-####",
  },
  {
    name: "Malta",
    code: "MT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mt.svg",
    phoneCode: "356",
    phoneMask: "+356-####-####",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mh.svg",
    phoneCode: "692",
    phoneMask: "+692-###-####",
  },
  {
    name: "Mauritania",
    code: "MR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mr.svg",
    phoneCode: "222",
    phoneMask: "+222-##-##-####",
  },
  {
    name: "Mauritius",
    code: "MU",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mu.svg",
    phoneCode: "230",
    phoneMask: "+230-###-####",
  },
  {
    name: "Mexico",
    code: "MX",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mx.svg",
    phoneCode: "52",
    phoneMask: "+52-##-##-####",
  },
  {
    name: "Micronesia",
    code: "FM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/fm.svg",
    phoneCode: "691",
    phoneMask: "+691-###-####",
  },
  {
    name: "Moldova",
    code: "MD",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/md.svg",
    phoneCode: "373",
    phoneMask: "+373-####-####",
  },
  {
    name: "Monaco",
    code: "MC",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mc.svg",
    phoneCode: "377",
    phoneMask: "+377-##-###-###",
  },
  {
    name: "Mongolia",
    code: "MN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mn.svg",
    phoneCode: "976",
    phoneMask: "+976-##-##-####",
  },
  {
    name: "Montenegro",
    code: "ME",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/me.svg",
    phoneCode: "382",
    phoneMask: "+382-##-###-###",
  },
  {
    name: "Morocco",
    code: "MA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ma.svg",
    phoneCode: "212",
    phoneMask: "+212-##-####-###",
  },
  {
    name: "Mozambique",
    code: "MZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mz.svg",
    phoneCode: "258",
    phoneMask: "+258-##-###-###",
  },
  {
    name: "Myanmar",
    code: "MM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mm.svg",
    phoneCode: "95",
    phoneMask: "+95-###-###",
  },
  {
    name: "Namibia",
    code: "NA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/na.svg",
    phoneCode: "264",
    phoneMask: "+264-##-###-####",
  },
  {
    name: "Nauru",
    code: "NR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/nr.svg",
    phoneCode: "674",
    phoneMask: "+674-###-####",
  },
  {
    name: "Nepal",
    code: "NP",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/np.svg",
    phoneCode: "977",
    phoneMask: "+977-##-###-###",
  },
  {
    name: "Netherlands",
    code: "NL",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/nl.svg",
    phoneCode: "31",
    phoneMask: "+31-##-###-####",
  },
  {
    name: "New Zealand",
    code: "NZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/nz.svg",
    phoneCode: "64",
    phoneMask: "+64 (###) ###-####",
  },
  {
    name: "Nicaragua",
    code: "NI",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ni.svg",
    phoneCode: "505",
    phoneMask: "+505-####-####",
  },
  {
    name: "Niger",
    code: "NE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ne.svg",
    phoneCode: "227",
    phoneMask: "+227-##-##-####",
  },
  {
    name: "Nigeria",
    code: "NG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ng.svg",
    phoneCode: "234",
    phoneMask: "+234 (###) ###-####",
  },
  {
    name: "North Korea",
    code: "KP",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/kp.svg",
    phoneCode: "850",
    phoneMask: "+850-####-#############",
  },
  {
    name: "North Macedonia",
    code: "MK",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/mk.svg",
    phoneCode: "389",
    phoneMask: "+389-##-###-###",
  },
  {
    name: "Norway",
    code: "NO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/no.svg",
    phoneCode: "47",
    phoneMask: "+47 (###) ##-###",
  },
  {
    name: "Oman",
    code: "OM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/om.svg",
    phoneCode: "968",
    phoneMask: "+968-##-###-###",
  },
  {
    name: "Pakistan",
    code: "PK",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/pk.svg",
    phoneCode: "92",
    phoneMask: "+92 (###) ###-####",
  },
  {
    name: "Palau",
    code: "PW",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/pw.svg",
    phoneCode: "680",
    phoneMask: "+680-###-####",
  },
  {
    name: "Panama",
    code: "PA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/pa.svg",
    phoneCode: "507",
    phoneMask: "+507-###-####",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/pg.svg",
    phoneCode: "675",
    phoneMask: "+675 (###) ##-###",
  },
  {
    name: "Paraguay",
    code: "PY",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/py.svg",
    phoneCode: "595",
    phoneMask: "+595 (###) ###-###",
  },
  {
    name: "Peru",
    code: "PE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/pe.svg",
    phoneCode: "51",
    phoneMask: "+51 (###) ###-###",
  },
  {
    name: "Philippines",
    code: "PH",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ph.svg",
    phoneCode: "63",
    phoneMask: "+63 (###) ###-####",
  },
  {
    name: "Poland",
    code: "PL",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/pl.svg",
    phoneCode: "48",
    phoneMask: "+48 (###) ###-###",
  },
  {
    name: "Portugal",
    code: "PT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/pt.svg",
    phoneCode: "351",
    phoneMask: "+351-##-###-####",
  },
  {
    name: "Qatar",
    code: "QA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/qa.svg",
    phoneCode: "974",
    phoneMask: "+974-####-####",
  },
  {
    name: "Romania",
    code: "RO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ro.svg",
    phoneCode: "40",
    phoneMask: "+40-##-###-####",
  },
  {
    name: "Russia",
    code: "RU",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ru.svg",
    phoneCode: "7",
    phoneMask: "+7 (###) ###-##-##",
  },
  {
    name: "Rwanda",
    code: "RW",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/rw.svg",
    phoneCode: "250",
    phoneMask: "+250 (###) ###-###",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/kn.svg",
    phoneCode: "+1-869",
    phoneMask: "+1 (869) ###-####",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/lc.svg",
    phoneCode: "+1-758",
    phoneMask: "+1 (758) ###-####",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/vc.svg",
    phoneCode: "+1-784",
    phoneMask: "+1 (784) ###-####",
  },
  {
    name: "Samoa",
    code: "WS",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ws.svg",
    phoneCode: "685",
    phoneMask: "+685-##-####",
  },
  {
    name: "San Marino",
    code: "SM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sm.svg",
    phoneCode: "378",
    phoneMask: "+378-####-######",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/st.svg",
    phoneCode: "239",
    phoneMask: "+239-##-#####",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sa.svg",
    phoneCode: "966",
    phoneMask: "+966-#-###-####",
  },
  {
    name: "Senegal",
    code: "SN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sn.svg",
    phoneCode: "221",
    phoneMask: "+221-##-###-####",
  },
  {
    name: "Serbia",
    code: "RS",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/rs.svg",
    phoneCode: "381",
    phoneMask: "+381-##-###-####",
  },
  {
    name: "Seychelles",
    code: "SC",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sc.svg",
    phoneCode: "248",
    phoneMask: "+248-#-###-###",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sl.svg",
    phoneCode: "232",
    phoneMask: "+232-##-######",
  },
  {
    name: "Singapore",
    code: "SG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sg.svg",
    phoneCode: "65",
    phoneMask: "+65-####-####",
  },
  {
    name: "Slovakia",
    code: "SK",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sk.svg",
    phoneCode: "421",
    phoneMask: "+421 (###) ###-###",
  },
  {
    name: "Slovenia",
    code: "SI",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/si.svg",
    phoneCode: "386",
    phoneMask: "+386-##-###-###",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sb.svg",
    phoneCode: "677",
    phoneMask: "+677-#####",
  },
  {
    name: "Somalia",
    code: "SO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/so.svg",
    phoneCode: "252",
    phoneMask: "+252-#-###-###",
  },
  {
    name: "South Africa",
    code: "ZA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/za.svg",
    phoneCode: "27",
    phoneMask: "+27-##-###-####",
  },
  {
    name: "South Korea",
    code: "KR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/kr.svg",
    phoneCode: "82",
    phoneMask: "+82-##-###-####",
  },
  {
    name: "South Sudan",
    code: "SS",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ss.svg",
    phoneCode: "211",
    phoneMask: "+211-##-###-####",
  },
  {
    name: "Spain",
    code: "ES",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/es.svg",
    phoneCode: "34",
    phoneMask: "+34 (###) ###-###",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/lk.svg",
    phoneCode: "94",
    phoneMask: "+94-##-###-####",
  },
  {
    name: "Suriname",
    code: "SR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sr.svg",
    phoneCode: "597",
    phoneMask: "+597-###-###",
  },
  {
    name: "Sweden",
    code: "SE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/se.svg",
    phoneCode: "46",
    phoneMask: "+46-##-###-####",
  },
  {
    name: "Switzerland",
    code: "CH",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ch.svg",
    phoneCode: "41",
    phoneMask: "+41-##-###-####",
  },
  {
    name: "Syria",
    code: "SY",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/sy.svg",
    phoneCode: "963",
    phoneMask: "+963-##-####-###",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tj.svg",
    phoneCode: "992",
    phoneMask: "+992-##-###-####",
  },
  {
    name: "Tanzania",
    code: "TZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tz.svg",
    phoneCode: "255",
    phoneMask: "+255-##-###-####",
  },
  {
    name: "Thailand",
    code: "TH",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/th.svg",
    phoneCode: "66",
    phoneMask: "+66-##-###-###",
  },
  {
    name: "Togo",
    code: "TG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tg.svg",
    phoneCode: "228",
    phoneMask: "+228-##-###-###",
  },
  {
    name: "Tonga",
    code: "TO",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/to.svg",
    phoneCode: "676",
    phoneMask: "+676-#####",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tt.svg",
    phoneCode: "+1-868",
    phoneMask: "+1 (868) ###-####",
  },
  {
    name: "Tunisia",
    code: "TN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tn.svg",
    phoneCode: "216",
    phoneMask: "+216-##-###-###",
  },
  {
    name: "Turkey",
    code: "TR",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tr.svg",
    phoneCode: "90",
    phoneMask: "+90 (###) ###-####",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tm.svg",
    phoneCode: "993",
    phoneMask: "+993-#-###-####",
  },
  {
    name: "Tuvalu",
    code: "TV",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/tv.svg",
    phoneCode: "688",
    phoneMask: "+688-2####",
  },
  {
    name: "Uganda",
    code: "UG",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ug.svg",
    phoneCode: "256",
    phoneMask: "+256 (###) ###-###",
  },
  {
    name: "Ukraine",
    code: "UA",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ua.svg",
    phoneCode: "380",
    phoneMask: "+380 (##) ###-##-##",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ae.svg",
    phoneCode: "971",
    phoneMask: "+971-#-###-####",
  },
  {
    name: "United Kingdom",
    code: "GB",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/gb.svg",
    phoneCode: "44",
  },
  {
    name: "United States",
    code: "US",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/us.svg",
    phoneCode: "1",
    phoneMask: "+1 (###) ###-####",
  },
  {
    name: "Uruguay",
    code: "UY",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/uy.svg",
    phoneCode: "598",
    phoneMask: "+598-#-###-##-##",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/uz.svg",
    phoneCode: "998",
    phoneMask: "+998-##-###-####",
  },
  {
    name: "Vanuatu",
    code: "VU",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/vu.svg",
    phoneCode: "678",
    phoneMask: "+678-#####",
  },
  {
    name: "Venezuela",
    code: "VE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ve.svg",
    phoneCode: "58",
    phoneMask: "+58 (###) ###-####",
  },
  {
    name: "Vietnam",
    code: "VN",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/vn.svg",
    phoneCode: "84",
    phoneMask: "+84 (###) ####-###",
  },
  {
    name: "Yemen",
    code: "YE",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/ye.svg",
    phoneCode: "967",
    phoneMask: "+967-##-###-###",
  },
  {
    name: "Zambia",
    code: "ZM",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/zm.svg",
    phoneCode: "260",
    phoneMask: "+260-##-###-####",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    flag: "https://cdn.jsdelivr.net/gh/lipis/flag-icons/flags/4x3/zw.svg",
    phoneCode: "263",
    phoneMask: "+263-#-######",
  },
];

/**
 * Phone code options for the select component.
 */
export const phoneCodeOptions: SelectItemType[] = countries.map((country) => ({
  id: country.code,
  label: country.code,
}));

/**
 * Country options for the select component.
 */
export const countriesOptions: SelectItemType[] = countries.map((country) => ({
  id: country.code,
  label: country.name,
  icon: (props: HTMLAttributes<HTMLImageElement>) => <img {...props} src={country.flag} alt={`${country.name} flag`} />,
}));

export default countries;
